# Generated by Django 3.1.3 on 2020-11-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50)),
                ('week', models.IntegerField()),
                ('team', models.CharField(max_length=3)),
                ('games', models.IntegerField()),
                ('dropbacks', models.IntegerField()),
                ('att', models.IntegerField()),
                ('comp', models.IntegerField()),
                ('drops', models.IntegerField()),
                ('comDrop', models.DecimalField(decimal_places=1, max_digits=4)),
                ('yds', models.IntegerField()),
                ('passYds300Games', models.IntegerField()),
                ('depthAim', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tds', models.IntegerField()),
                ('td40s', models.IntegerField()),
                ('td50s', models.IntegerField()),
                ('ints', models.IntegerField()),
                ('sks', models.IntegerField()),
                ('rushCarries', models.IntegerField()),
                ('rushYds', models.IntegerField()),
                ('rushTds', models.IntegerField()),
                ('rushTd40s', models.IntegerField()),
                ('fumbles', models.IntegerField()),
                ('patConversions', models.IntegerField()),
                ('patAttempts', models.IntegerField()),
                ('fantasyPts', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ptsPerDb', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'passer',
            },
        ),
        migrations.CreateModel(
            name='RushRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50)),
                ('week', models.IntegerField()),
                ('team', models.CharField(max_length=3)),
                ('games', models.IntegerField()),
                ('position', models.CharField(max_length=2)),
                ('recTarg', models.IntegerField()),
                ('recRec', models.IntegerField()),
                ('recRec40s', models.IntegerField()),
                ('recYds', models.IntegerField()),
                ('recYds100Games', models.IntegerField()),
                ('recTds', models.IntegerField()),
                ('recTd40s', models.IntegerField()),
                ('recDrops', models.IntegerField()),
                ('catch', models.DecimalField(decimal_places=1, max_digits=4)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ypt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ypr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rac', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rushCarries', models.IntegerField()),
                ('rush40s', models.IntegerField()),
                ('rushYds', models.IntegerField()),
                ('rushYds100Games', models.IntegerField()),
                ('rushTds', models.IntegerField()),
                ('rushTd40s', models.IntegerField()),
                ('ypc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yac', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rushTa', models.IntegerField()),
                ('tat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fumbles', models.IntegerField()),
                ('patConversions', models.IntegerField()),
                ('patAttempts', models.IntegerField()),
                ('fantasyPts', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ptsPerSnap', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ptsPerTouch', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'rushrec',
            },
        ),
    ]
