# Generated by Django 3.0.5 on 2020-12-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passer',
            options={'managed': False},
        ),
    ]
