# Generated by Django 3.0.5 on 2020-12-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20201201_2048'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passer',
            table='week10p',
        ),
    ]
