# Generated by Django 3.0.5 on 2020-12-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20201201_2049'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passer',
            table='passer',
        ),
    ]
