# Generated by Django 3.0.5 on 2020-11-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201114_1011'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='week1p',
            table='week1p',
        ),
    ]
