# Generated by Django 3.0.5 on 2020-11-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201114_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
