# Generated by Django 3.0.5 on 2020-11-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('name', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=3)),
                ('position', models.CharField(max_length=2)),
                ('fantasypts', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
